"""
backend/services/quiz_generator.py
Purpose: Generate an in-app quiz (test JSON) from an assessment report.
         Reads data/ap_csa_reference_bank.md for relevant topic content,
         generates quiz questions with Claude, and appends them back
         to the reference bank for future reuse.
Docs: https://docs.anthropic.com/en/api/messages
Sample input:  generate_quiz("Bella", "session_1", report_data, [], client)
Sample output: data/tests/generated/bella_data_quiz_2.json
               (also appends new questions to data/ap_csa_reference_bank.md)
"""
import json
import os
import re
from pathlib import Path
from datetime import datetime, timezone
from typing import Optional
from loguru import logger

ROOT = Path(__file__).parent.parent.parent
REFERENCE_BANK_PATH = ROOT / "data" / "ap_csa_reference_bank.md"
GENERATED_DIR = ROOT / "data" / "tests" / "generated"

QUIZ_GENERATION_PROMPT = """You are an expert AP Computer Science A question writer.

Student: {student_name}
Assessment weak topics: {weak_topics}
Performance notes: {performance_notes}
Take-home assignment covered these topics: {takehome_topics}

Relevant reference bank content for these topics:
---
{reference_bank_excerpt}
---

Generate exactly 8 quiz questions (6 multiple_choice or code_trace, 2 frq) that test whether the student improved on their weak topics after the take-home assignment.

The questions should:
1. Build on each other — later questions can reference concepts from earlier ones
2. Directly test the specific weak topics identified
3. Increase in difficulty (questions 1-3 easier, 4-6 medium, 7-8 harder FRQs)
4. Follow AP CSA exam style — realistic distractors, one clear correct answer

Return raw JSON only (no markdown fences) matching this EXACT schema:
{{
  "questions": [
    {{
      "id": "quiz_q1",
      "type": "code_trace",
      "topic_tags": ["<topic>"],
      "unit": <1-10>,
      "prompt": "<question text>",
      "code_block": "<Java code or null>",
      "options": {{"A": "<text>", "B": "<text>", "C": "<text>", "D": "<text>"}},
      "answer_key": "<A|B|C|D>",
      "explanation": "<why this is correct and what the common mistake is>",
      "guiding_questions": [
        {{"id": "quiz_q1_g1", "text": "<debugging hint question>"}}
      ]
    }}
  ]
}}

For frq type questions use:
  "options": {{}},
  "answer_key": "",
  "code_block": null,
  "parts": [
    {{
      "part": "a",
      "description": "<what to write>",
      "points": 4,
      "starter_code": "<Java skeleton with blanks>",
      "test_cases": [{{"description": "<test description>", "expected_output": "<output>"}}],
      "line_concepts": {{}}
    }}
  ],
  "total_points": 9

Guiding questions are shown if the student gets the answer wrong — make them hint at the concept, not give away the answer directly.
"""

REFERENCE_BANK_APPEND_TEMPLATE = """\n\n---\n\n## GENERATED QUESTIONS — {topic} (from {student_name} session {session_id}, {date})\n\n> Auto-generated by quiz_generator.py. Review before using in future sessions.\n\n{questions_markdown}\n"""


def _extract_reference_sections(topics: list) -> str:
    """Extract topic-relevant sections from the reference bank."""
    if not REFERENCE_BANK_PATH.exists():
        return "Reference bank not found."
    content = REFERENCE_BANK_PATH.read_text()
    excerpts = []
    for topic in topics:
        topic_display = topic.replace('_', ' ')
        pattern = re.compile(
            r'(#{1,3}[^\n]*' + re.escape(topic_display) + r'[^\n]*\n)(.*?)(?=\n#{1,3}|\Z)',
            re.IGNORECASE | re.DOTALL
        )
        for heading, body in pattern.findall(content):
            excerpts.append(f"{heading}{body[:800].strip()}")
    if not excerpts:
        return "No specific reference content found for these topics."
    return "\n\n---\n\n".join(excerpts)


def _append_to_reference_bank(questions: list, student_name: str, session_id: str) -> None:
    """Append generated questions to the reference bank grouped by topic."""
    if not REFERENCE_BANK_PATH.exists():
        return

    topics: dict = {}
    for q in questions:
        for tag in q.get("topic_tags", []):
            if tag not in topics:
                topics[tag] = []
            topics[tag].append(q)

    new_content = ""
    for topic, qs in topics.items():
        q_markdown_parts = []
        for q in qs:
            opts = "\n".join(
                f"  - {k}) {v}" for k, v in q.get("options", {}).items()
            )
            code = q.get("code_block") or ""
            code_section = f"\n```java\n{code}\n```\n" if code else ""
            q_markdown_parts.append(
                f"### [{q['id']}] {q.get('prompt', '')}\n"
                f"**Type:** {q['type']}  **Unit:** {q.get('unit', '?')}\n"
                f"{code_section}\n"
                f"**Options:**\n{opts}\n\n"
                f"**Answer:** {q.get('answer_key', 'N/A')}\n"
                f"**Explanation:** {q.get('explanation', '')}\n"
            )
        new_content += REFERENCE_BANK_APPEND_TEMPLATE.format(
            topic=topic.replace('_', ' ').title(),
            student_name=student_name.capitalize(),
            session_id=session_id,
            date=datetime.now(timezone.utc).strftime("%Y-%m-%d"),
            questions_markdown="\n\n".join(q_markdown_parts),
        )

    with open(REFERENCE_BANK_PATH, "a") as f:
        f.write(new_content)
    total = sum(len(v) for v in topics.values())
    logger.info(f"Appended {total} questions to reference bank")


def generate_quiz(
    student_name: str,
    session_id: str,
    report: dict,
    takehome_topics: list,
    client,
) -> Optional[Path]:
    """
    Generate quiz JSON and append questions to reference bank.
    Returns path to generated quiz JSON, or None on failure.
    Safe to call as a FastAPI BackgroundTask — logs errors, never raises.
    """
    try:
        from config import STUDENTS_DIR

        safe = re.sub(r'[^\w]', '_', student_name.lower().strip())
        student_dir = STUDENTS_DIR / f"{safe}_data"
        iteration = int(session_id.split("_")[1])
        quiz_iteration = iteration + 1

        weak_topics = report.get("weak_topics", [])
        uncertain = [t for t in report.get("topic_analysis", [])
                     if t["confidence_level"] in ("uncertain", "struggling")]
        performance_notes = (
            "; ".join(f"{t['topic']}: {t['notes']}" for t in uncertain)
            or "Student showed hesitation on several topics."
        )

        reference_excerpt = _extract_reference_sections(weak_topics)

        prompt = QUIZ_GENERATION_PROMPT.format(
            student_name=student_name.capitalize(),
            weak_topics=", ".join(weak_topics),
            performance_notes=performance_notes,
            takehome_topics=(
                ", ".join(takehome_topics) if takehome_topics else "same as weak topics"
            ),
            reference_bank_excerpt=reference_excerpt,
        )

        with client.messages.stream(
            model="claude-opus-4-6",
            max_tokens=8192,
            messages=[{"role": "user", "content": prompt}],
        ) as stream:
            raw = stream.get_final_text().strip()

        if raw.startswith("```"):
            raw = re.sub(r'^```[a-z]*\n?', '', raw)
            raw = re.sub(r'\n?```$', '', raw)
        data = json.loads(raw.strip())

        GENERATED_DIR.mkdir(parents=True, exist_ok=True)
        quiz_test_id = f"{student_dir.name}_quiz_{quiz_iteration}"
        quiz = {
            "test_id": quiz_test_id,
            "title": f"{student_name.capitalize()} — Quiz (Session {quiz_iteration})",
            "session_type": "quiz",
            "created_at": datetime.now(timezone.utc).isoformat(),
            "questions": data["questions"],
        }
        quiz_path = GENERATED_DIR / f"{quiz_test_id}.json"
        quiz_path.write_text(json.dumps(quiz, indent=2))
        logger.info(f"Quiz saved -> {quiz_path}")

        _append_to_reference_bank(data["questions"], student_name, session_id)

        return quiz_path

    except Exception as e:
        logger.error(f"Quiz generation failed for {student_name}/{session_id}: {e}")
        return None


if __name__ == "__main__":
    import sys
    import anthropic
    from dotenv import load_dotenv

    load_dotenv(ROOT / "backend" / ".env")
    name = sys.argv[1] if len(sys.argv) > 1 else "bella"
    sid = sys.argv[2] if len(sys.argv) > 2 else "session_1"
    safe = re.sub(r'[^\w]', '_', name.lower())
    report_path = (
        ROOT / "data" / "students" / f"{safe}_data" / f"report_{sid.split('_')[1]}.json"
    )
    if not report_path.exists():
        print(f"No report at {report_path}")
        sys.exit(1)
    report_data = json.loads(report_path.read_text())
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        print("ANTHROPIC_API_KEY not set")
        sys.exit(1)
    c = anthropic.Anthropic(api_key=api_key, timeout=300.0)
    result = generate_quiz(name, sid, report_data, [], c)
    print(f"Generated: {result}")
